import { pgTable, text, boolean, integer, uuid, jsonb, timestamp, date, index } from "drizzle-orm/pg-core";
import { organizations } from "./organizations";
export const reminderCategories = pgTable("reminder_categories", {
    id: uuid("id").defaultRandom().primaryKey(),
    orgId: uuid("org_id").references(() => organizations.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    nameEn: text("name_en"),
    icon: text("icon").default("Bell"),
    color: text("color").default("#5b9bd5"),
    sortOrder: integer("sort_order").default(0),
    isSystem: boolean("is_system").default(false),
    isActive: boolean("is_active").default(true),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});
export const reminderTemplates = pgTable("reminder_templates", {
    id: uuid("id").defaultRandom().primaryKey(),
    orgId: uuid("org_id").references(() => organizations.id, { onDelete: "cascade" }),
    categoryId: uuid("category_id").references(() => reminderCategories.id, { onDelete: "set null" }),
    name: text("name").notNull(),
    nameEn: text("name_en"),
    description: text("description"),
    icon: text("icon").default("Bell"),
    color: text("color"),
    defaultTitle: text("default_title"),
    defaultDescription: text("default_description"),
    defaultRemindBeforeDays: jsonb("default_remind_before_days").default([30, 7, 1]),
    defaultRecurrence: text("default_recurrence"),
    defaultChannels: jsonb("default_channels").default(["dashboard"]),
    smsTemplate: text("sms_template"),
    emailSubjectTemplate: text("email_subject_template"),
    emailBodyTemplate: text("email_body_template"),
    extraFields: jsonb("extra_fields"),
    availableVariables: jsonb("available_variables").default(["org_name", "due_date", "title", "days_remaining"]),
    tags: jsonb("tags").default([]),
    applicableTo: jsonb("applicable_to").default(["all"]),
    isSystem: boolean("is_system").default(false),
    isActive: boolean("is_active").default(true),
    sortOrder: integer("sort_order").default(0),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
    createdBy: uuid("created_by"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});
export const orgReminders = pgTable("org_reminders", {
    id: uuid("id").defaultRandom().primaryKey(),
    orgId: uuid("org_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
    templateId: uuid("template_id").references(() => reminderTemplates.id, { onDelete: "set null" }),
    categoryId: uuid("category_id").references(() => reminderCategories.id, { onDelete: "set null" }),
    title: text("title").notNull(),
    description: text("description"),
    icon: text("icon").default("Bell"),
    color: text("color"),
    tags: jsonb("tags").default([]),
    dueDate: date("due_date").notNull(),
    remindBeforeDays: jsonb("remind_before_days").default([30, 7, 1]),
    isRecurring: boolean("is_recurring").default(false),
    recurrence: text("recurrence"),
    recurrenceInterval: integer("recurrence_interval"),
    recurrenceEndDate: date("recurrence_end_date"),
    nextOccurrence: date("next_occurrence"),
    status: text("status").default("upcoming"),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    completedBy: uuid("completed_by"),
    snoozedUntil: date("snoozed_until"),
    linkedType: text("linked_type"),
    linkedId: uuid("linked_id"),
    linkedLabel: text("linked_label"),
    extraData: jsonb("extra_data").default({}),
    notificationChannels: jsonb("notification_channels").default(["dashboard"]),
    notificationsLog: jsonb("notifications_log").default([]),
    priority: text("priority").default("medium"),
    createdByType: text("created_by_type").default("system"),
    createdBy: uuid("created_by"),
    notes: text("notes"),
    attachments: jsonb("attachments").default([]),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
}, (table) => [
    index("org_reminders_org_idx").on(table.orgId),
    index("org_reminders_due_idx").on(table.dueDate),
    index("org_reminders_status_idx").on(table.status),
]);
//# sourceMappingURL=reminders.js.map