// ============================================================
// INTEGRATION REGISTRY — كل التكاملات المدعومة في نسق
// ============================================================

export interface IntegrationField {
  key: string;
  label: string;
  type: "text" | "password" | "select";
  required: boolean;
  options?: { value: string; label: string }[];
}

export interface IntegrationEntry {
  provider: string;
  name: string;          // Arabic name
  nameEn: string;
  category: string;
  description: string;
  region: "local" | "global" | "both";
  logo: string;          // provider key used by frontend for logo/initials
  fields: IntegrationField[];
  features: string[];
}

export const INTEGRATION_REGISTRY: IntegrationEntry[] = [

  // ── الدفع ─────────────────────────────────────────────────────
  {
    provider: "moyasar",
    name: "ميسر",
    nameEn: "Moyasar",
    category: "payment",
    description: "بوابة دفع سعودية تدعم مدى، فيزا، ماستركارد، وآبل باي",
    region: "local",
    logo: "moyasar",
    fields: [
      { key: "publishable_key", label: "المفتاح العام", type: "text", required: true },
      { key: "secret_key", label: "المفتاح السري", type: "password", required: true },
    ],
    features: ["mada", "visa", "mastercard", "apple_pay", "stc_pay"],
  },
  {
    provider: "myfatoorah",
    name: "ماي فاتورة",
    nameEn: "MyFatoorah",
    category: "payment",
    description: "بوابة دفع خليجية تدعم بطاقات متعددة ومحافظ إلكترونية",
    region: "local",
    logo: "myfatoorah",
    fields: [
      { key: "api_key", label: "مفتاح API", type: "password", required: true },
      { key: "mode", label: "البيئة", type: "select", required: true, options: [{ value: "live", label: "إنتاج" }, { value: "test", label: "اختبار" }] },
    ],
    features: ["knet", "benefit", "mada", "visa", "mastercard"],
  },
  {
    provider: "tap",
    name: "Tap Payments",
    nameEn: "Tap Payments",
    category: "payment",
    description: "بوابة دفع منطقة الخليج — تدعم بطاقات وSTC Pay",
    region: "local",
    logo: "tap",
    fields: [
      { key: "secret_key", label: "المفتاح السري", type: "password", required: true },
      { key: "publishable_key", label: "المفتاح العام", type: "text", required: true },
    ],
    features: ["visa", "mastercard", "stc_pay", "benefit"],
  },
  {
    provider: "hyperpay",
    name: "HyperPay",
    nameEn: "HyperPay",
    category: "payment",
    description: "بوابة دفع تدعم أكثر من 100 طريقة دفع في المنطقة",
    region: "local",
    logo: "hyperpay",
    fields: [
      { key: "entity_id", label: "Entity ID", type: "text", required: true },
      { key: "access_token", label: "Access Token", type: "password", required: true },
      { key: "mode", label: "البيئة", type: "select", required: true, options: [{ value: "live", label: "إنتاج" }, { value: "test", label: "اختبار" }] },
    ],
    features: ["mada", "visa", "mastercard", "stc_pay"],
  },
  {
    provider: "stripe",
    name: "Stripe",
    nameEn: "Stripe",
    category: "payment",
    description: "بوابة الدفع العالمية الأشهر — تدعم أكثر من 135 عملة",
    region: "global",
    logo: "stripe",
    fields: [
      { key: "publishable_key", label: "Publishable Key", type: "text", required: true },
      { key: "secret_key", label: "Secret Key", type: "password", required: true },
      { key: "webhook_secret", label: "Webhook Secret", type: "password", required: false },
    ],
    features: ["visa", "mastercard", "apple_pay", "google_pay"],
  },
  {
    provider: "paypal",
    name: "PayPal",
    nameEn: "PayPal",
    category: "payment",
    description: "منصة دفع عالمية تدعم 200+ دولة",
    region: "global",
    logo: "paypal",
    fields: [
      { key: "client_id", label: "Client ID", type: "text", required: true },
      { key: "client_secret", label: "Client Secret", type: "password", required: true },
      { key: "mode", label: "البيئة", type: "select", required: true, options: [{ value: "live", label: "إنتاج" }, { value: "sandbox", label: "اختبار" }] },
    ],
    features: ["paypal_balance", "credit_card"],
  },
  {
    provider: "square",
    name: "Square",
    nameEn: "Square",
    category: "payment",
    description: "حلول دفع متكاملة للأعمال الصغيرة والمتوسطة",
    region: "global",
    logo: "square",
    fields: [
      { key: "access_token", label: "Access Token", type: "password", required: true },
      { key: "location_id", label: "Location ID", type: "text", required: true },
    ],
    features: ["visa", "mastercard", "apple_pay", "google_pay"],
  },
  {
    provider: "tabby",
    name: "تابي",
    nameEn: "Tabby",
    category: "payment",
    description: "اشتر الآن وادفع لاحقاً — BNPL للسوق الخليجي",
    region: "local",
    logo: "tabby",
    fields: [
      { key: "public_key", label: "المفتاح العام", type: "text", required: true },
      { key: "secret_key", label: "المفتاح السري", type: "password", required: true },
    ],
    features: ["buy_now_pay_later", "installments"],
  },
  {
    provider: "tamara",
    name: "تمارا",
    nameEn: "Tamara",
    category: "payment",
    description: "تقسيط بدون فوائد — الشريك المالي للتجارة الإلكترونية في السعودية",
    region: "local",
    logo: "tamara",
    fields: [
      { key: "api_token", label: "API Token", type: "password", required: true },
      { key: "notification_key", label: "Notification Key", type: "password", required: false },
    ],
    features: ["installments_3", "installments_6", "pay_later"],
  },

  // ── الفوترة الإلكترونية ────────────────────────────────────
  {
    provider: "zatca_cleartax",
    name: "ClearTax ZATCA",
    nameEn: "ClearTax ZATCA",
    category: "e_invoicing",
    description: "منصة تكامل ZATCA Phase 2 — فواتير ضريبية متوافقة",
    region: "local",
    logo: "zatca_cleartax",
    fields: [
      { key: "api_key", label: "API Key", type: "password", required: true },
      { key: "vat_number", label: "الرقم الضريبي", type: "text", required: true },
    ],
    features: ["zatca_phase2", "xml_signing", "reporting"],
  },
  {
    provider: "zatca_qeemah",
    name: "قيمة ZATCA",
    nameEn: "Qeemah ZATCA",
    category: "e_invoicing",
    description: "خدمة إصدار الفواتير الإلكترونية المتوافقة مع هيئة الزكاة",
    region: "local",
    logo: "zatca_qeemah",
    fields: [
      { key: "api_key", label: "API Key", type: "password", required: true },
      { key: "seller_id", label: "معرف البائع", type: "text", required: true },
    ],
    features: ["zatca_phase2", "b2b", "b2c"],
  },
  {
    provider: "zatca_tax2gov",
    name: "Tax2Gov ZATCA",
    nameEn: "Tax2Gov ZATCA",
    category: "e_invoicing",
    description: "ربط مباشر مع منظومة ZATCA للفوترة الإلكترونية",
    region: "local",
    logo: "zatca_tax2gov",
    fields: [
      { key: "certificate", label: "الشهادة الرقمية", type: "password", required: true },
      { key: "private_key", label: "المفتاح الخاص", type: "password", required: true },
    ],
    features: ["zatca_phase2", "digital_signature"],
  },

  // ── الشحن ─────────────────────────────────────────────────────
  {
    provider: "smsa",
    name: "SMSA Express",
    nameEn: "SMSA Express",
    category: "shipping",
    description: "شركة SMSA للشحن السريع داخل المملكة العربية السعودية",
    region: "local",
    logo: "smsa",
    fields: [
      { key: "passkey", label: "Pass Key", type: "password", required: true },
      { key: "sender_name", label: "اسم المرسل", type: "text", required: true },
    ],
    features: ["domestic", "tracking", "cod"],
  },
  {
    provider: "aramex",
    name: "أرامكس",
    nameEn: "Aramex",
    category: "shipping",
    description: "خدمات الشحن والتوصيل الدولي من أرامكس",
    region: "both",
    logo: "aramex",
    fields: [
      { key: "username", label: "اسم المستخدم", type: "text", required: true },
      { key: "password", label: "كلمة المرور", type: "password", required: true },
      { key: "account_number", label: "رقم الحساب", type: "text", required: true },
    ],
    features: ["domestic", "international", "tracking", "cod"],
  },
  {
    provider: "spl",
    name: "البريد السعودي (سبل)",
    nameEn: "Saudi Post (SPL)",
    category: "shipping",
    description: "شركة البريد السعودي — التوصيل الوطني لكامل المملكة",
    region: "local",
    logo: "spl",
    fields: [
      { key: "api_key", label: "API Key", type: "password", required: true },
      { key: "account_id", label: "معرف الحساب", type: "text", required: true },
    ],
    features: ["domestic", "tracking", "cod"],
  },
  {
    provider: "fetchr",
    name: "Fetchr",
    nameEn: "Fetchr",
    category: "shipping",
    description: "خدمة توصيل ذكية تعمل بالعناوين البديلة",
    region: "local",
    logo: "fetchr",
    fields: [
      { key: "api_key", label: "API Key", type: "password", required: true },
    ],
    features: ["domestic", "tracking", "smart_address"],
  },
  {
    provider: "jt",
    name: "J&T Express",
    nameEn: "J&T Express",
    category: "shipping",
    description: "شركة شحن سريعة متخصصة في التجارة الإلكترونية",
    region: "both",
    logo: "jt",
    fields: [
      { key: "customer_code", label: "Customer Code", type: "text", required: true },
      { key: "secret_key", label: "Secret Key", type: "password", required: true },
    ],
    features: ["domestic", "international", "tracking", "cod"],
  },
  {
    provider: "dhl",
    name: "DHL",
    nameEn: "DHL",
    category: "shipping",
    description: "شركة DHL للشحن الدولي — الأكبر عالمياً",
    region: "global",
    logo: "dhl",
    fields: [
      { key: "api_key", label: "API Key", type: "password", required: true },
      { key: "account_number", label: "رقم الحساب", type: "text", required: true },
    ],
    features: ["international", "express", "tracking"],
  },
  {
    provider: "fedex",
    name: "FedEx",
    nameEn: "FedEx",
    category: "shipping",
    description: "خدمات الشحن السريع الدولي من FedEx",
    region: "global",
    logo: "fedex",
    fields: [
      { key: "api_key", label: "API Key", type: "password", required: true },
      { key: "secret_key", label: "Secret Key", type: "password", required: true },
      { key: "account_number", label: "رقم الحساب", type: "text", required: true },
    ],
    features: ["international", "express", "tracking", "cod"],
  },
  {
    provider: "ups",
    name: "UPS",
    nameEn: "UPS",
    category: "shipping",
    description: "خدمات الشحن والتوصيل الدولي من UPS",
    region: "global",
    logo: "ups",
    fields: [
      { key: "username", label: "اسم المستخدم", type: "text", required: true },
      { key: "password", label: "كلمة المرور", type: "password", required: true },
      { key: "access_key", label: "Access Key", type: "password", required: true },
    ],
    features: ["international", "express", "tracking"],
  },

  // ── توصيل الطعام ───────────────────────────────────────────
  {
    provider: "jahez",
    name: "جاهز",
    nameEn: "Jahez",
    category: "delivery",
    description: "منصة جاهز لتوصيل الطعام في المملكة العربية السعودية",
    region: "local",
    logo: "jahez",
    fields: [
      { key: "api_key", label: "API Key", type: "password", required: true },
      { key: "restaurant_id", label: "معرف المطعم", type: "text", required: true },
    ],
    features: ["food_delivery", "order_sync", "menu_sync"],
  },
  {
    provider: "hungerstation",
    name: "HungerStation",
    nameEn: "HungerStation",
    category: "delivery",
    description: "منصة HungerStation لتوصيل الطعام",
    region: "local",
    logo: "hungerstation",
    fields: [
      { key: "api_key", label: "API Key", type: "password", required: true },
      { key: "vendor_id", label: "معرف البائع", type: "text", required: true },
    ],
    features: ["food_delivery", "order_sync"],
  },
  {
    provider: "toyou",
    name: "ToYou",
    nameEn: "ToYou",
    category: "delivery",
    description: "خدمة توصيل ToYou — الشحن بالباركود",
    region: "local",
    logo: "toyou",
    fields: [
      { key: "api_key", label: "API Key", type: "password", required: true },
    ],
    features: ["last_mile", "tracking", "cod"],
  },

  // ── نقاط البيع ─────────────────────────────────────────────
  {
    provider: "foodics",
    name: "فودكس",
    nameEn: "Foodics",
    category: "pos",
    description: "نظام نقاط بيع متكامل لقطاع المطاعم والمقاهي",
    region: "local",
    logo: "foodics",
    fields: [
      { key: "api_key", label: "API Key", type: "password", required: true },
      { key: "branch_id", label: "معرف الفرع", type: "text", required: false },
    ],
    features: ["order_sync", "menu_sync", "reports"],
  },
  {
    provider: "square_pos",
    name: "Square POS",
    nameEn: "Square POS",
    category: "pos",
    description: "نقطة بيع متكاملة من Square",
    region: "global",
    logo: "square_pos",
    fields: [
      { key: "access_token", label: "Access Token", type: "password", required: true },
      { key: "location_id", label: "Location ID", type: "text", required: true },
    ],
    features: ["order_sync", "inventory_sync", "payment"],
  },
  {
    provider: "loyverse",
    name: "Loyverse POS",
    nameEn: "Loyverse POS",
    category: "pos",
    description: "نقطة بيع مجانية للمطاعم والمتاجر الصغيرة",
    region: "global",
    logo: "loyverse",
    fields: [
      { key: "access_token", label: "Access Token", type: "password", required: true },
    ],
    features: ["order_sync", "inventory_sync", "loyalty"],
  },

  // ── المراسلة ────────────────────────────────────────────────
  {
    provider: "unifonic",
    name: "يونيفونيك",
    nameEn: "Unifonic",
    category: "messaging",
    description: "منصة سعودية للرسائل النصية وواتساب",
    region: "local",
    logo: "unifonic",
    fields: [
      { key: "app_sid", label: "App SID", type: "text", required: true },
      { key: "sender_id", label: "Sender ID", type: "text", required: true },
    ],
    features: ["sms", "whatsapp", "otp"],
  },
  {
    provider: "twilio",
    name: "Twilio",
    nameEn: "Twilio",
    category: "messaging",
    description: "منصة عالمية للرسائل النصية والمكالمات",
    region: "global",
    logo: "twilio",
    fields: [
      { key: "account_sid", label: "Account SID", type: "text", required: true },
      { key: "auth_token", label: "Auth Token", type: "password", required: true },
      { key: "from_number", label: "رقم المرسل", type: "text", required: true },
    ],
    features: ["sms", "whatsapp", "voice", "otp"],
  },
  {
    provider: "resend",
    name: "Resend",
    nameEn: "Resend",
    category: "messaging",
    description: "خدمة إرسال بريد إلكتروني للمطورين",
    region: "global",
    logo: "resend",
    fields: [
      { key: "api_key", label: "API Key", type: "password", required: true },
      { key: "from_email", label: "بريد المرسل", type: "text", required: true },
    ],
    features: ["email", "transactional", "templates"],
  },
  {
    provider: "sendgrid",
    name: "SendGrid",
    nameEn: "SendGrid",
    category: "messaging",
    description: "منصة البريد الإلكتروني الأكبر عالمياً من Twilio",
    region: "global",
    logo: "sendgrid",
    fields: [
      { key: "api_key", label: "API Key", type: "password", required: true },
      { key: "from_email", label: "بريد المرسل", type: "text", required: true },
      { key: "from_name", label: "اسم المرسل", type: "text", required: false },
    ],
    features: ["email", "transactional", "marketing"],
  },
  {
    provider: "mailgun",
    name: "Mailgun",
    nameEn: "Mailgun",
    category: "messaging",
    description: "خدمة إرسال البريد الإلكتروني للمطورين",
    region: "global",
    logo: "mailgun",
    fields: [
      { key: "api_key", label: "API Key", type: "password", required: true },
      { key: "domain", label: "النطاق", type: "text", required: true },
    ],
    features: ["email", "transactional", "tracking"],
  },
  {
    provider: "whatsapp_meta",
    name: "واتساب Business API",
    nameEn: "WhatsApp Meta API",
    category: "messaging",
    description: "API واتساب الرسمي من Meta للأعمال",
    region: "global",
    logo: "whatsapp_meta",
    fields: [
      { key: "phone_number_id", label: "Phone Number ID", type: "text", required: true },
      { key: "access_token", label: "Access Token", type: "password", required: true },
      { key: "verify_token", label: "Verify Token", type: "text", required: false },
    ],
    features: ["whatsapp", "templates", "webhooks"],
  },
  {
    provider: "fcm",
    name: "Firebase Cloud Messaging",
    nameEn: "Firebase Cloud Messaging",
    category: "messaging",
    description: "إشعارات Push عبر Firebase من Google",
    region: "global",
    logo: "fcm",
    fields: [
      { key: "server_key", label: "Server Key", type: "password", required: true },
      { key: "project_id", label: "Project ID", type: "text", required: true },
    ],
    features: ["push_notifications", "android", "ios"],
  },
  {
    provider: "onesignal",
    name: "OneSignal",
    nameEn: "OneSignal",
    category: "messaging",
    description: "منصة إشعارات Push متعددة القنوات",
    region: "global",
    logo: "onesignal",
    fields: [
      { key: "app_id", label: "App ID", type: "text", required: true },
      { key: "api_key", label: "REST API Key", type: "password", required: true },
    ],
    features: ["push_notifications", "sms", "email"],
  },

  // ── المحاسبة ────────────────────────────────────────────────
  {
    provider: "qoyod",
    name: "قيود",
    nameEn: "Qoyod",
    category: "accounting",
    description: "نظام محاسبي سحابي سعودي متوافق مع ZATCA",
    region: "local",
    logo: "qoyod",
    fields: [
      { key: "api_key", label: "API Key", type: "password", required: true },
    ],
    features: ["invoices", "expenses", "reports", "zatca"],
  },
  {
    provider: "wafeq",
    name: "وافق",
    nameEn: "Wafeq",
    category: "accounting",
    description: "برنامج محاسبة سحابي للشركات السعودية والخليجية",
    region: "local",
    logo: "wafeq",
    fields: [
      { key: "api_key", label: "API Key", type: "password", required: true },
    ],
    features: ["invoices", "expenses", "vat", "reports"],
  },
  {
    provider: "daftra",
    name: "دفترة",
    nameEn: "Daftra",
    category: "accounting",
    description: "نظام محاسبة ومبيعات للشركات العربية",
    region: "local",
    logo: "daftra",
    fields: [
      { key: "api_key", label: "API Key", type: "password", required: true },
      { key: "account_subdomain", label: "النطاق الفرعي", type: "text", required: true },
    ],
    features: ["invoices", "expenses", "inventory"],
  },
  {
    provider: "quickbooks",
    name: "QuickBooks",
    nameEn: "QuickBooks",
    category: "accounting",
    description: "نظام محاسبة Intuit الأشهر عالمياً",
    region: "global",
    logo: "quickbooks",
    fields: [
      { key: "client_id", label: "Client ID", type: "text", required: true },
      { key: "client_secret", label: "Client Secret", type: "password", required: true },
      { key: "realm_id", label: "Realm ID", type: "text", required: true },
    ],
    features: ["invoices", "expenses", "payroll", "reports"],
  },
  {
    provider: "xero",
    name: "Xero",
    nameEn: "Xero",
    category: "accounting",
    description: "نظام محاسبة سحابي للشركات الصغيرة والمتوسطة",
    region: "global",
    logo: "xero",
    fields: [
      { key: "client_id", label: "Client ID", type: "text", required: true },
      { key: "client_secret", label: "Client Secret", type: "password", required: true },
    ],
    features: ["invoices", "expenses", "bank_feeds", "reports"],
  },
  {
    provider: "zoho_books",
    name: "Zoho Books",
    nameEn: "Zoho Books",
    category: "accounting",
    description: "نظام محاسبة من Zoho مع ميزات إدارة أعمال متكاملة",
    region: "global",
    logo: "zoho_books",
    fields: [
      { key: "client_id", label: "Client ID", type: "text", required: true },
      { key: "client_secret", label: "Client Secret", type: "password", required: true },
      { key: "organization_id", label: "Organization ID", type: "text", required: true },
    ],
    features: ["invoices", "expenses", "inventory", "reports"],
  },

  // ── إدارة علاقات العملاء ───────────────────────────────────
  {
    provider: "hubspot",
    name: "HubSpot",
    nameEn: "HubSpot",
    category: "crm",
    description: "منصة CRM الأشهر عالمياً مع أدوات تسويق ومبيعات",
    region: "global",
    logo: "hubspot",
    fields: [
      { key: "access_token", label: "Access Token", type: "password", required: true },
    ],
    features: ["contacts", "deals", "email", "analytics"],
  },
  {
    provider: "salesforce",
    name: "Salesforce",
    nameEn: "Salesforce",
    category: "crm",
    description: "منصة CRM للمؤسسات الكبيرة",
    region: "global",
    logo: "salesforce",
    fields: [
      { key: "client_id", label: "Client ID", type: "text", required: true },
      { key: "client_secret", label: "Client Secret", type: "password", required: true },
      { key: "instance_url", label: "Instance URL", type: "text", required: true },
    ],
    features: ["contacts", "opportunities", "automation"],
  },
  {
    provider: "zoho_crm",
    name: "Zoho CRM",
    nameEn: "Zoho CRM",
    category: "crm",
    description: "نظام CRM من Zoho لإدارة العملاء والمبيعات",
    region: "global",
    logo: "zoho_crm",
    fields: [
      { key: "client_id", label: "Client ID", type: "text", required: true },
      { key: "client_secret", label: "Client Secret", type: "password", required: true },
    ],
    features: ["contacts", "leads", "deals", "reports"],
  },

  // ── التقويم ─────────────────────────────────────────────────
  {
    provider: "google_calendar",
    name: "تقويم Google",
    nameEn: "Google Calendar",
    category: "calendar",
    description: "ربط تقويم Google لمزامنة المواعيد والحجوزات",
    region: "global",
    logo: "google_calendar",
    fields: [
      { key: "client_id", label: "Client ID", type: "text", required: true },
      { key: "client_secret", label: "Client Secret", type: "password", required: true },
      { key: "calendar_id", label: "Calendar ID", type: "text", required: false },
    ],
    features: ["events", "sync", "notifications"],
  },
  {
    provider: "caldav",
    name: "CalDAV",
    nameEn: "CalDAV",
    category: "calendar",
    description: "بروتوكول تقويم مفتوح — متوافق مع iCloud وOutlook وغيرها",
    region: "global",
    logo: "caldav",
    fields: [
      { key: "server_url", label: "Server URL", type: "text", required: true },
      { key: "username", label: "اسم المستخدم", type: "text", required: true },
      { key: "password", label: "كلمة المرور", type: "password", required: true },
    ],
    features: ["events", "sync", "two_way"],
  },
  {
    provider: "outlook_calendar",
    name: "تقويم Outlook",
    nameEn: "Outlook Calendar",
    category: "calendar",
    description: "ربط تقويم Microsoft Outlook / Office 365",
    region: "global",
    logo: "outlook_calendar",
    fields: [
      { key: "client_id", label: "Client ID", type: "text", required: true },
      { key: "client_secret", label: "Client Secret", type: "password", required: true },
      { key: "tenant_id", label: "Tenant ID", type: "text", required: false },
    ],
    features: ["events", "sync", "two_way"],
  },

  // ── التخزين ─────────────────────────────────────────────────
  {
    provider: "aws_s3",
    name: "Amazon S3",
    nameEn: "Amazon S3",
    category: "storage",
    description: "تخزين الملفات والوسائط على Amazon S3",
    region: "global",
    logo: "aws_s3",
    fields: [
      { key: "access_key_id", label: "Access Key ID", type: "text", required: true },
      { key: "secret_access_key", label: "Secret Access Key", type: "password", required: true },
      { key: "bucket", label: "Bucket Name", type: "text", required: true },
      { key: "region", label: "Region", type: "text", required: true },
    ],
    features: ["file_storage", "cdn", "backups"],
  },
  {
    provider: "gcs",
    name: "Google Cloud Storage",
    nameEn: "Google Cloud Storage",
    category: "storage",
    description: "تخزين الملفات على Google Cloud",
    region: "global",
    logo: "gcs",
    fields: [
      { key: "service_account_key", label: "Service Account JSON", type: "password", required: true },
      { key: "bucket", label: "Bucket Name", type: "text", required: true },
    ],
    features: ["file_storage", "cdn", "backups"],
  },
  {
    provider: "cloudflare_r2",
    name: "Cloudflare R2",
    nameEn: "Cloudflare R2",
    category: "storage",
    description: "تخزين الملفات بدون رسوم خروج على Cloudflare",
    region: "global",
    logo: "cloudflare_r2",
    fields: [
      { key: "account_id", label: "Account ID", type: "text", required: true },
      { key: "access_key_id", label: "Access Key ID", type: "text", required: true },
      { key: "secret_access_key", label: "Secret Access Key", type: "password", required: true },
      { key: "bucket", label: "Bucket Name", type: "text", required: true },
    ],
    features: ["file_storage", "cdn", "zero_egress"],
  },

  // ── الخرائط ─────────────────────────────────────────────────
  {
    provider: "google_maps",
    name: "خرائط Google",
    nameEn: "Google Maps",
    category: "maps",
    description: "خرائط وعناوين دقيقة من Google",
    region: "global",
    logo: "google_maps",
    fields: [
      { key: "api_key", label: "API Key", type: "password", required: true },
    ],
    features: ["geocoding", "directions", "places"],
  },
  {
    provider: "mapbox",
    name: "Mapbox",
    nameEn: "Mapbox",
    category: "maps",
    description: "خرائط تفاعلية قابلة للتخصيص",
    region: "global",
    logo: "mapbox",
    fields: [
      { key: "access_token", label: "Access Token", type: "password", required: true },
    ],
    features: ["geocoding", "directions", "custom_maps"],
  },

  // ── التحليلات ───────────────────────────────────────────────
  {
    provider: "ga4",
    name: "Google Analytics 4",
    nameEn: "Google Analytics 4",
    category: "analytics",
    description: "تحليلات الموقع والتطبيق من Google — الجيل الرابع",
    region: "global",
    logo: "ga4",
    fields: [
      { key: "measurement_id", label: "Measurement ID", type: "text", required: true },
    ],
    features: ["page_views", "events", "conversions", "funnels"],
  },
  {
    provider: "gtm",
    name: "Google Tag Manager",
    nameEn: "Google Tag Manager",
    category: "analytics",
    description: "إدارة علامات التتبع بدون تعديل الكود",
    region: "global",
    logo: "gtm",
    fields: [
      { key: "container_id", label: "Container ID", type: "text", required: true },
    ],
    features: ["tag_management", "triggers", "variables"],
  },
  {
    provider: "facebook_pixel",
    name: "Meta Pixel",
    nameEn: "Meta Pixel (Facebook)",
    category: "analytics",
    description: "تتبع التحويلات وإعادة الاستهداف على Facebook وInstagram",
    region: "global",
    logo: "facebook_pixel",
    fields: [
      { key: "pixel_id", label: "Pixel ID", type: "text", required: true },
      { key: "access_token", label: "Access Token", type: "password", required: false },
    ],
    features: ["events", "conversions", "retargeting"],
  },
  {
    provider: "snapchat_pixel",
    name: "Snapchat Pixel",
    nameEn: "Snapchat Pixel",
    category: "analytics",
    description: "تتبع التحويلات على Snapchat",
    region: "both",
    logo: "snapchat_pixel",
    fields: [
      { key: "pixel_id", label: "Pixel ID", type: "text", required: true },
    ],
    features: ["events", "conversions"],
  },
  {
    provider: "tiktok_pixel",
    name: "TikTok Pixel",
    nameEn: "TikTok Pixel",
    category: "analytics",
    description: "تتبع التحويلات على TikTok",
    region: "global",
    logo: "tiktok_pixel",
    fields: [
      { key: "pixel_id", label: "Pixel ID", type: "text", required: true },
      { key: "access_token", label: "Access Token", type: "password", required: false },
    ],
    features: ["events", "conversions"],
  },
  {
    provider: "twitter_pixel",
    name: "X (Twitter) Pixel",
    nameEn: "X (Twitter) Pixel",
    category: "analytics",
    description: "تتبع التحويلات على منصة X",
    region: "global",
    logo: "twitter_pixel",
    fields: [
      { key: "pixel_id", label: "Pixel ID", type: "text", required: true },
    ],
    features: ["events", "conversions"],
  },
  {
    provider: "google_ads",
    name: "Google Ads",
    nameEn: "Google Ads",
    category: "analytics",
    description: "ربط إعلانات Google لتتبع التحويلات",
    region: "global",
    logo: "google_ads",
    fields: [
      { key: "conversion_id", label: "Conversion ID", type: "text", required: true },
      { key: "conversion_label", label: "Conversion Label", type: "text", required: true },
    ],
    features: ["conversions", "remarketing"],
  },
  {
    provider: "clarity",
    name: "Microsoft Clarity",
    nameEn: "Microsoft Clarity",
    category: "analytics",
    description: "تسجيل جلسات المستخدم وخرائط الحرارة من Microsoft",
    region: "global",
    logo: "clarity",
    fields: [
      { key: "project_id", label: "Project ID", type: "text", required: true },
    ],
    features: ["session_recording", "heatmaps", "insights"],
  },

  // ── الأتمتة ─────────────────────────────────────────────────
  {
    provider: "zapier",
    name: "Zapier",
    nameEn: "Zapier",
    category: "automation",
    description: "ربط ترميز OS بأكثر من 5000 تطبيق عبر Zapier",
    region: "global",
    logo: "zapier",
    fields: [
      { key: "webhook_url", label: "Webhook URL", type: "text", required: true },
    ],
    features: ["triggers", "actions", "multi_step"],
  },
  {
    provider: "make",
    name: "Make (Integromat)",
    nameEn: "Make",
    category: "automation",
    description: "أتمتة قوية مع تدفقات عمل مرئية من Make",
    region: "global",
    logo: "make",
    fields: [
      { key: "webhook_url", label: "Webhook URL", type: "text", required: true },
    ],
    features: ["scenarios", "triggers", "data_transform"],
  },
  {
    provider: "n8n",
    name: "n8n",
    nameEn: "n8n",
    category: "automation",
    description: "أداة أتمتة مفتوحة المصدر قابلة للنشر الذاتي",
    region: "global",
    logo: "n8n",
    fields: [
      { key: "webhook_url", label: "Webhook URL", type: "text", required: true },
      { key: "auth_header", label: "Auth Header", type: "password", required: false },
    ],
    features: ["workflows", "self_hosted", "triggers"],
  },

  // ── التجارة الإلكترونية ────────────────────────────────────
  {
    provider: "shopify",
    name: "Shopify",
    nameEn: "Shopify",
    category: "ecommerce",
    description: "منصة التجارة الإلكترونية العالمية الأشهر",
    region: "global",
    logo: "shopify",
    fields: [
      { key: "shop_domain", label: "Shop Domain", type: "text", required: true },
      { key: "access_token", label: "Admin API Token", type: "password", required: true },
    ],
    features: ["products", "orders", "customers", "inventory"],
  },
  {
    provider: "woocommerce",
    name: "WooCommerce",
    nameEn: "WooCommerce",
    category: "ecommerce",
    description: "إضافة التجارة الإلكترونية الأشهر لـ WordPress",
    region: "global",
    logo: "woocommerce",
    fields: [
      { key: "site_url", label: "رابط الموقع", type: "text", required: true },
      { key: "consumer_key", label: "Consumer Key", type: "text", required: true },
      { key: "consumer_secret", label: "Consumer Secret", type: "password", required: true },
    ],
    features: ["products", "orders", "customers"],
  },
  {
    provider: "salla",
    name: "سلة",
    nameEn: "Salla",
    category: "ecommerce",
    description: "منصة التجارة الإلكترونية السعودية — سلة",
    region: "local",
    logo: "salla",
    fields: [
      { key: "client_id", label: "Client ID", type: "text", required: true },
      { key: "client_secret", label: "Client Secret", type: "password", required: true },
    ],
    features: ["products", "orders", "customers", "zatca"],
  },
  {
    provider: "zid",
    name: "زد",
    nameEn: "Zid",
    category: "ecommerce",
    description: "منصة التجارة الإلكترونية السعودية — زد",
    region: "local",
    logo: "zid",
    fields: [
      { key: "access_token", label: "Access Token", type: "password", required: true },
      { key: "store_id", label: "Store ID", type: "text", required: true },
    ],
    features: ["products", "orders", "customers"],
  },

  // ── الموارد البشرية ─────────────────────────────────────────
  {
    provider: "jisr",
    name: "جسر HR",
    nameEn: "Jisr HR",
    category: "hr",
    description: "منصة إدارة الموارد البشرية والرواتب السعودية",
    region: "local",
    logo: "jisr",
    fields: [
      { key: "api_key", label: "API Key", type: "password", required: true },
      { key: "company_id", label: "Company ID", type: "text", required: true },
    ],
    features: ["employees", "payroll", "attendance", "leaves"],
  },
  {
    provider: "mudad",
    name: "مدد",
    nameEn: "Mudad",
    category: "hr",
    description: "منصة مدد لحماية الأجور وإدارة الرواتب في السعودية",
    region: "local",
    logo: "mudad",
    fields: [
      { key: "cr_number", label: "رقم السجل التجاري", type: "text", required: true },
      { key: "iban", label: "رقم الآيبان", type: "text", required: true },
    ],
    features: ["wage_protection", "payroll", "wps"],
  },

  // ── الضيافة والإقامة ────────────────────────────────────────
  {
    provider: "ical_sync",
    name: "iCalendar Sync",
    nameEn: "iCalendar Sync",
    category: "hospitality",
    description: "مزامنة التوفر مع أي منصة عبر رابط iCal — يعمل مع Booking وAirbnb وGathern",
    region: "both",
    logo: "ical_sync",
    fields: [
      { key: "ical_url", label: "رابط iCal (للاستيراد)", type: "text", required: false },
    ],
    features: ["availability_sync", "booking_import", "export_ical"],
  },
  {
    provider: "gathern",
    name: "جاذر إن",
    nameEn: "Gathern",
    category: "hospitality",
    description: "أول منصة مرخصة للإقامة المشتركة في السعودية — 50,000+ عقار",
    region: "local",
    logo: "gathern",
    fields: [
      { key: "ical_url", label: "رابط iCal من جاذر إن", type: "text", required: false },
      { key: "api_key", label: "API Key (اختياري)", type: "password", required: false },
    ],
    features: ["availability_sync", "booking_sync", "pricing_sync"],
  },
  {
    provider: "booking_com",
    name: "Booking.com",
    nameEn: "Booking.com",
    category: "hospitality",
    description: "منصة الحجز الأكبر عالمياً — مزامنة توفر وأسعار وحجوزات",
    region: "global",
    logo: "booking_com",
    fields: [
      { key: "username", label: "Connectivity Username", type: "text", required: true },
      { key: "password", label: "Connectivity Password", type: "password", required: true },
      { key: "hotel_id", label: "Hotel ID", type: "text", required: true },
    ],
    features: ["availability_sync", "rate_sync", "booking_sync", "reviews"],
  },
  {
    provider: "airbnb",
    name: "Airbnb",
    nameEn: "Airbnb",
    category: "hospitality",
    description: "مزامنة التوفر والحجوزات مع Airbnb عبر iCal أو API",
    region: "global",
    logo: "airbnb",
    fields: [
      { key: "ical_url", label: "رابط iCal من Airbnb", type: "text", required: false },
      { key: "access_token", label: "Access Token (للـ API الكامل)", type: "password", required: false },
    ],
    features: ["availability_sync", "booking_sync", "messaging"],
  },
  {
    provider: "channex",
    name: "Channex",
    nameEn: "Channex",
    category: "hospitality",
    description: "مدير قنوات يربط Booking + Airbnb + Expedia + 50 منصة بتكامل واحد",
    region: "global",
    logo: "channex",
    fields: [
      { key: "api_key", label: "API Key", type: "password", required: true },
      { key: "property_id", label: "Property ID", type: "text", required: true },
    ],
    features: ["channel_manager", "availability_sync", "rate_sync", "booking_sync"],
  },
  {
    provider: "cloudbeds",
    name: "Cloudbeds",
    nameEn: "Cloudbeds",
    category: "hospitality",
    description: "PMS + Channel Manager + Booking Engine متكامل",
    region: "global",
    logo: "cloudbeds",
    fields: [
      { key: "access_token", label: "Access Token", type: "password", required: true },
      { key: "property_id", label: "Property ID", type: "text", required: true },
    ],
    features: ["pms", "channel_manager", "booking_engine", "reporting"],
  },
  {
    provider: "guesty",
    name: "Guesty",
    nameEn: "Guesty",
    category: "hospitality",
    description: "channel manager متخصص بالإقامة القصيرة — Airbnb, Booking, VRBO",
    region: "global",
    logo: "guesty",
    fields: [
      { key: "api_token", label: "API Token", type: "password", required: true },
    ],
    features: ["short_term_rental", "channel_manager", "automation", "guest_messaging"],
  },
  {
    provider: "expedia",
    name: "Expedia",
    nameEn: "Expedia",
    category: "hospitality",
    description: "مزامنة مع Expedia Partner Central — أسعار وتوفر وحجوزات",
    region: "global",
    logo: "expedia",
    fields: [
      { key: "api_key", label: "API Key", type: "password", required: true },
      { key: "hotel_id", label: "Hotel ID", type: "text", required: true },
    ],
    features: ["availability_sync", "rate_sync", "booking_sync"],
  },

  // ── حكومي ───────────────────────────────────────────────────
  {
    provider: "absher",
    name: "أبشر",
    nameEn: "Absher",
    category: "gov",
    description: "بوابة أبشر للخدمات الحكومية السعودية",
    region: "local",
    logo: "absher",
    fields: [
      { key: "api_key", label: "API Key", type: "password", required: true },
    ],
    features: ["identity_verification", "visa_check"],
  },
  {
    provider: "nafath",
    name: "نفاذ",
    nameEn: "Nafath",
    category: "gov",
    description: "منصة نفاذ الوطنية للهوية الرقمية",
    region: "local",
    logo: "nafath",
    fields: [
      { key: "client_id", label: "Client ID", type: "text", required: true },
      { key: "client_secret", label: "Client Secret", type: "password", required: true },
    ],
    features: ["identity_verification", "kyc", "digital_signature"],
  },
  {
    provider: "elm",
    name: "شركة علم",
    nameEn: "ELM",
    category: "gov",
    description: "شركة علم للخدمات التقنية الحكومية",
    region: "local",
    logo: "elm",
    fields: [
      { key: "api_key", label: "API Key", type: "password", required: true },
      { key: "app_id", label: "App ID", type: "text", required: true },
    ],
    features: ["identity_verification", "cr_verification", "iqama_check"],
  },
];

// Lookup by provider key
export function getIntegrationEntry(provider: string): IntegrationEntry | undefined {
  return INTEGRATION_REGISTRY.find((e) => e.provider === provider);
}

// All unique categories
export const INTEGRATION_CATEGORIES = [
  ...new Set(INTEGRATION_REGISTRY.map((e) => e.category)),
];
